### ISSUE TITLE
(Ecto.NoResultsError) expected at least one result but got none in query:

### ISSUE THREAD

**Issue by niccolox** [cbh123/emoji#21]
getting this error in local and also on fly

investigating now

```
[debug] QUERY OK source="predictions" db=0.4ms idle=1217.6ms
SELECT count(*) FROM "predictions" AS p0 WHERE (NOT (p0."image_embedding") IS NULL) []
↳ Emoji.Embeddings.Worker.should_generate_image_embedding?/0, at: lib/emoji/embeddings/worker.ex:36
[debug] QUERY OK source="predictions" db=0.4ms idle=1218.3ms
SELECT count(*) FROM "predictions" AS p0 WHERE (NOT (p0."embedding") IS NULL) []
↳ Emoji.Embeddings.Worker.should_generate_text_embedding?/0, at: lib/emoji/embeddings/worker.ex:28
[debug] QUERY OK source="predictions" db=0.2ms idle=1219.0ms
SELECT p0."id", p0."no_bg_output", p0."emoji_output", p0."prompt", p0."uuid", p0."score", p0."count_votes", p0."is_featured", p0."local_user_id", p0."moderation_score", p0."moderator", p0."embedding", p0."image_embedding", p0."embedding_model", p0."inserted_at", p0."updated_at" FROM "predictions" AS p0 WHERE (((p0."embedding" IS NULL) AND NOT (p0."emoji_output" IS NULL)) AND (p0."score" != 10)) ORDER BY RANDOM() LIMIT 1 []
↳ Emoji.Embeddings.Worker.handle_info/2, at: lib/emoji/embeddings/worker.ex:81
[error] GenServer #PID<0.730.0> terminating
** (Ecto.NoResultsError) expected at least one result but got none in query:

from p0 in Emoji.Predictions.Prediction,
  where: is_nil(p0.embedding) and not is_nil(p0.emoji_output) and p0.score != 10,
  order_by: [asc: fragment("RANDOM()")],
  limit: 1

    (ecto 3.10.3) lib/ecto/repo/queryable.ex:161: Ecto.Repo.Queryable.one!/3
    (emoji 0.1.0) lib/emoji/embeddings/worker.ex:81: Emoji.Embeddings.Worker.handle_info/2
    (stdlib 3.17.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17.1) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :work
State: %{}
```

**Comment by niccolox** [comment]
fails silently, moving on

closing this one
