### ISSUE TITLE
How to Host

### ISSUE THREAD

**Issue by jimmybrancaccio** [cbh123/emoji#8]
Heyo! This is a super neat app and I saw it looks like it should be possible to deploy it to Fly.io. I've attempted to do this but I don't think I've got it completely working.

1. I cloned the repo.
2. Ran `mix setup`.
3. I moved the `fly.toml` file aside - `mv fly.toml fly.toml.bak`.
4. Then ran `flyctl launch`. I deployed it with a PostgreSQL database though I don't think that is necessary - correct me if I am wrong.
5. I added a secret via the Fly.io web dashboard for `REPLICATE_API_TOKEN` and filled it in with the token I obtained from https://replicate.com. I redeployed the app so it would use the token.
6. Upon visiting my instance https://custom-emoji.fly.dev I can type something in, and it will generate the emoji however about 3 seconds later the page refreshes and says something about not being able to find the internet and reconnecting.

<img width="1143" alt="Screenshot 2023-09-12 at 11 18 38" src="https://github.com/cbh123/emoji/assets/405585/36c392fd-051a-43a1-af86-e579a5245ce1">

Any ideas on getting this to work would be very much appreciated. If there's any other information or details I can provide to help troubleshoot please don't hesitate to let me know!

Thanks,

**Comment by cbh123** [comment]
Hm were you able to run it locally? If you run `fly logs --tail` what does the error say?

**Comment by jimmybrancaccio** [comment]
Hey @cbh123! I wasn't able to run it locally as it does seem to rely on PostgreSQL in some sort of capacity (??) and I didn't want to install it on my MacBook. That said, here's the logs from when I make a request via the web UI for an emoji:

```
2023-09-13T20:15:33Z app[148ed770fe2258] dfw [info]20:15:33.052 [error] GenServer #PID<0.2225.0> terminating
2023-09-13T20:15:33Z app[148ed770fe2258] dfw [info]** (System.EnvError) could not fetch environment variable "TELEGRAM_BOT_TOKEN" because it is not set
2023-09-13T20:15:33Z app[148ed770fe2258] dfw [info]    (emoji 0.1.0) lib/emoji_web/live/home_live.ex:122: EmojiWeb.HomeLive.handle_info/2
2023-09-13T20:15:33Z app[148ed770fe2258] dfw [info]    (phoenix_live_view 0.18.18) lib/phoenix_live_view/channel.ex:276: Phoenix.LiveView.Channel.handle_info/2
2023-09-13T20:15:33Z app[148ed770fe2258] dfw [info]    (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
2023-09-13T20:15:33Z app[148ed770fe2258] dfw [info]    (stdlib 5.0.2) proc_lib.erl:251: :proc_lib.wake_up/3
2023-09-13T20:15:33Z app[148ed770fe2258] dfw [info]Last message: {:background_removed, %Emoji.Predictions.Prediction{__meta__: #Ecto.Schema.Metadata<:loaded, "predictions">, id: 17, no_bg_output: nil, emoji_output: "https://pbxt.replicate.delivery/VLodCzwE0n5mNNV0kgwUhwNS3ez5iK188IQUYGef0QjAT5HjA/out-0.png", prompt: "A TOK emoji of a german shepherd", uuid: "gdxh7xdbaendnfaao6mehx366m", score: 0, count_votes: 0, is_featured: nil, local_user_id: "lmfacroslmsdiai963e", moderation_score: 0, moderator: "fofr/prompt-classifier:1ffac777bf2c1f5a4a5073faf389fefe59a8b9326b3ca329e9d576cce658a00f", inserted_at: ~N[2023-09-13 20:15:20], updated_at: ~N[2023-09-13 20:15:30]}, "https://replicate.delivery/pbxt/lHw9mHecId17M6WQN7d8G2qRtllkWaVBkzklfhf2IHjJT5HjA/out.png"}
```

**Comment by cbh123** [comment]
Ah! I see the issue. I'm requiring a `TELEGRAM_BOT_TOKEN` (I have a helper functions that messages me the latest emojis). I just updated things so that this isn't necessary anymore — things should work for you now! Let me know. 

https://github.com/cbh123/emoji/commit/b20b138621ff20c69297dd48602555880ade46b5

**Comment by jimmybrancaccio** [comment]
Definitely getting closer, I think! I thought it was that BOT_TOKEN or something with Telegram causing the issue but I didn't want to say anything as I have zero experience in this language haha

So now I think it's still trying to do something with Telegram, perhaps it's still trying to send the message and it has issues. I am seeing the following in the logs as well as it still throws up that "can't find the internet message":

```
2023-09-14T15:36:07Z app[148ed770fe2258] dfw [info]15:36:07.117 [error] GenServer #PID<0.2642.0> terminating
2023-09-14T15:36:07Z app[148ed770fe2258] dfw [info]** (MatchError) no match of right hand side value: :error
2023-09-14T15:36:07Z app[148ed770fe2258] dfw [info]    (emoji 0.1.0) lib/emoji_web/live/home_live.ex:215: EmojiWeb.HomeLive.send_telegram_message/4
2023-09-14T15:36:07Z app[148ed770fe2258] dfw [info]    (emoji 0.1.0) lib/emoji_web/live/home_live.ex:122: EmojiWeb.HomeLive.handle_info/2
2023-09-14T15:36:07Z app[148ed770fe2258] dfw [info]    (phoenix_live_view 0.18.18) lib/phoenix_live_view/channel.ex:276: Phoenix.LiveView.Channel.handle_info/2
2023-09-14T15:36:07Z app[148ed770fe2258] dfw [info]    (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
2023-09-14T15:36:07Z app[148ed770fe2258] dfw [info]    (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
2023-09-14T15:36:07Z app[148ed770fe2258] dfw [info]    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
2023-09-14T15:36:07Z app[148ed770fe2258] dfw [info]Last message: {:background_removed, %Emoji.Predictions.Prediction{__meta__: #Ecto.Schema.Metadata<:loaded, "predictions">, id: 20, no_bg_output: nil, emoji_output: "https://pbxt.replicate.delivery/8eOSwPE137ySEadTu9EvwoOAPE9Wkfq7VK5c5ljyhP0ipNkRA/out-0.png", prompt: "A TOK emoji of a horse", uuid: "uatyzolbiyr3unwps4mzhe7dbq", score: 0, count_votes: 0, is_featured: nil, local_user_id: "lmfacroslmsdiai963e", moderation_score: 0, moderator: "fofr/prompt-classifier:1ffac777bf2c1f5a4a5073faf389fefe59a8b9326b3ca329e9d576cce658a00f", embedding: nil, embedding_model: nil, inserted_at: ~N[2023-09-14 15:35:54], updated_at: ~N[2023-09-14 15:36:04]}, "https://replicate.delivery/pbxt/CBZdWFrqmZIxA5LhgWwQwZAgVhVvy1NU2QH2TeXU09Gz0GyIA/out.png"}
```

I tried setting the method (or what I think is called a method 😝) to this:

```elixir
  def send_telegram_message(prompt, image, id, score) do
    1 == 1
  end
```

and it seems to work better, I don't get that "can't find the internet message" and the page redirect/refresh. You can try it here to see what happens - https://custom-emoji.fly.dev.

**Comment by jimmybrancaccio** [comment]
Just a quick update, I commented out line 122 in `lib/emoji_web/live/home_live.ex`:

```elixir
# send_telegram_message(prediction.prompt, image, prediction.id, prediction.moderation_score)
```

I also setup a Cloudflare R2 bucket and added those related env variables to my Fly.io secrets.
